Repository DeveloperAcademy-POSTECH/MacC-Team-1010, pull requests merged in 2023-11, with the labels that each got.

#33 #31/ MakHoly 데이터 타입 구현
  Projects/Core/Sources/Models/MakHoly/Award.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/LikeState.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/Review.swift
  Projects/Core/Sources/Models/MakHoly/Taste.swift
Labels: ✨ 기능

#37 #31/ MakHoly 프로퍼티 public 변환
  Projects/Core/Sources/Models/MakHoly/Award.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/Review.swift
  Projects/Core/Sources/Models/MakHoly/Taste.swift
Labels: 🐞 버그

#39 #29/ InformationView UI 구현
  Projects/Core/Sources/Common/Componets/DividerView.swift
  Projects/Core/Sources/Common/Componets/TasteRatingView.swift
  Projects/Core/Sources/Common/Componets/TasteScoreView.swift
  Projects/Core/Sources/Models/MakHoly/Award.swift
  Projects/Core/Sources/Models/MakHoly/LikeState.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/Taste.swift
  Projects/DesignSystem/Resources/Colors.xcassets/w85.colorset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scorelargeNull.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scorelargeNull.imageset/scorelargeNull.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini0.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini0.imageset/ScoreMini0.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini0.imageset/scoremini0.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini1.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini1.imageset/ScoreMini1.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini1.imageset/scoremini1.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini2.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini2.imageset/ScoreMini2.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini2.imageset/scoremini2.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini3.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini3.imageset/ScoreMini3.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini3.imageset/scoremini3.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini4.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini4.imageset/ScoreMini4.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini4.imageset/scoremini4.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini5.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini5.imageset/ScoreMini5.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoremini5.imageset/scoremini5.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoreminiNull.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoreminiNull.imageset/scoreminiNull.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall0.imageset/ScoreSmall0.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall1.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall1.imageset/ScoreSmall1.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall2.imageset/ScoreSmall2.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall3.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall3.imageset/ScoreSmall3.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall4.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall4.imageset/ScoreSmall4.svg
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall5.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Score/scoresmall5.imageset/ScoreSmall5.svg
  Projects/DesignSystem/Sources/Colors/Color.swift
  Projects/DesignSystem/Sources/Component/ScoreView.swift
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureInformation/Scene/Components/InfoAwardsView.swift
  Projects/FeatureInformation/Scene/Components/InfoIngredientsView.swift
  Projects/FeatureInformation/Scene/Components/InfoLinkView.swift
  Projects/FeatureInformation/Scene/Components/LikeControllerView.swift
  Projects/FeatureInformation/Scene/DetailModel/MakgeolliDetail.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/Makgeolli/InfoRow.swift
  Projects/FeatureInformation/Scene/Makgeolli/MakgeolliView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
Labels: ✨ 기능, 💄 UI

#41 #25/SearchView UI 구현
  Projects/Core/Sources/Common/Extensions/Double+.swift
  Projects/Core/Sources/Common/Extensions/Int+.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryControllerView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryListView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchSuggestionView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ✨ 기능, 💄 UI

#42 #35, #38/네트워크 구조 설계, Firebase 세팅 및 로직 구현
  Projects/App/Resources/GoogleService-Info.plist
  Projects/Core/Project.swift
  Projects/Core/Sources/Common/Extensions/Encodable+.swift
  Projects/Core/Sources/Error/NetworkError.swift
  Projects/Core/Sources/Models/Category/CategoryType.swift
  Projects/Core/Sources/Models/Characteristics/CharacteristicsType.swift
  Projects/Core/Sources/Models/MakHoly/Award.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/Comment.swift
  Projects/Core/Sources/Models/MakHoly/LikeState.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyMini.swift
  Projects/Core/Sources/Models/MakHoly/Review.swift
  Projects/Core/Sources/Models/MakHoly/Taste.swift
  Projects/Core/Sources/Models/Mock/MockData.swift
  Projects/Core/Sources/Models/Mock/MockModel.swift
  Projects/Core/Sources/Models/Price/PriceType.swift
  Projects/Core/Sources/Models/Region/RegionType.swift
  Projects/Core/Sources/Models/User/User.swift
  Projects/Core/Sources/Network/MakgeolliAPI.swift
  Projects/Core/Sources/Network/Request/MakgeolliInfoRequest.swift
  Projects/Core/Sources/Network/Request/MakgeolliListRequest.swift
  Projects/Core/Sources/Network/Response/MakgeolliInfoResponse.swift
  Projects/Core/Sources/Network/Response/MakgeolliListResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/Core/Sources/Utilities/MoyaCacheablePlugin.swift
  Projects/FeatureAuth/Project.swift
  Projects/FeatureCategory/Project.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/Hashtag/HashtagSingleView.swift
  Projects/FeatureCategory/Scene/Hashtag/HashtagView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureEncyclopedia/Project.swift
  Projects/FeatureHome/Project.swift
  Projects/FeatureHome/Scene/Characteristics/CharacteristicsView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemView.swift
  Projects/FeatureInformation/Project.swift
  Projects/FeatureProfile/Project.swift
  Projects/FeatureSearch/Project.swift
Labels: ✨ 기능

#43 Refactor / MakHoly 데이터 타입
  Projects/Core/Sources/Common/Componets/TasteScoreView.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/Comment.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyMini.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/Core/Sources/Network/Response/MakgeolliInfoResponse.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoContentView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureInformation/Scene/Components/InfoAwardsView.swift
  Projects/FeatureInformation/Scene/Components/InfoLinkView.swift
  Projects/FeatureInformation/Scene/Components/LikeControllerView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ♻️ 리팩토링, 🐞 버그

#32 #26/Data Model, Tab Bar구현
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureEncyclopedia/Model/ThumbnailModel.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/Tab/TabMenuView.swift
  Projects/FeatureEncyclopedia/Scene/Tab/TabNameView.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/Thumbnail.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
  Projects/FeatureEncyclopedia/Scene/View/BadView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/View/GoodView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
Labels: ✨ 기능, 💄 UI

#46 #44 / MakHolyImageView 구현
  Projects/Core/Sources/Common/Componets/MakHolyImageView.swift
  Projects/Core/Sources/Models/Category/CategoryType.swift
  Projects/Core/Sources/Models/Image/ImageRatioType.swift
  Projects/Core/Sources/Models/Image/ImageType.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/Comment.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyMini.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/Core/Sources/Models/User/User.swift
  Projects/DesignSystem/Sources/Colors/Color.swift
Labels: ✨ 기능, 💄 UI

#47 #34/Profile UI
  Projects/Feature/Project.swift
  Projects/FeatureOnboarding/Project.swift
  Projects/FeatureOnboarding/Scene/OnboardingView.swift
  Projects/FeatureProfile/Scene/MyInformation/MyInformationView.swift
  Projects/FeatureProfile/Scene/ProfileView.swift
  Projects/FeatureProfile/Scene/SettingList/SettingListView.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Project.swift
Labels: ✨ 기능, 💄 UI

#54 #53 디자인 시스템 구현 업데이트
  Projects/DesignSystem/Sources/Colors/Color+.swift
  Projects/DesignSystem/Sources/Text/Text.swift
Labels: ⚙️ 설정, 💄 UI

#57 #56/API 통신 로직 추가 및 네트워크 코드 리팩토링
  Projects/Core/Sources/Network/HomeAPI.swift
  Projects/Core/Sources/Network/MakgeolliAPI.swift
  Projects/Core/Sources/Network/Request/MakInfo/DetailRequest.swift
  Projects/Core/Sources/Network/Request/MakInfo/FindByFeaturesRequest.swift
  Projects/Core/Sources/Network/Request/MakInfo/MakLikesAndCommentsRequest.swift
  Projects/Core/Sources/Network/Request/MakInfo/MakListRequest.swift
  Projects/Core/Sources/Network/Request/User/CommentRequest.swift
  Projects/Core/Sources/Network/Request/User/EvaluateMakRequest.swift
  Projects/Core/Sources/Network/Request/User/GetUserMakFolderRequest.swift
  Projects/Core/Sources/Network/Request/User/UserRequest.swift
  Projects/Core/Sources/Network/Request/User/WishListRequest.swift
  Projects/Core/Sources/Network/Response/MakInfo/DetailResponse.swift
  Projects/Core/Sources/Network/Response/MakInfo/FindByFeaturesResponse.swift
  Projects/Core/Sources/Network/Response/MakInfo/MakLikesAndCommentsResponse.swift
  Projects/Core/Sources/Network/Response/MakInfo/MakListResponse.swift
  Projects/Core/Sources/Network/Response/Search/SearchResponse.swift
  Projects/Core/Sources/Network/Response/User/CommentResponse.swift
  Projects/Core/Sources/Network/Response/User/EvaluateMakResponse.swift
  Projects/Core/Sources/Network/Response/User/GetUserMakFolderResponse.swift
  Projects/Core/Sources/Network/Response/User/UserResponse.swift
  Projects/Core/Sources/Network/SearchAPI.swift
  Projects/Core/Sources/Network/UserAPI.swift
  Projects/Core/Sources/Repositories/HomeRepository.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/Core/Sources/Repositories/SearchRepository.swift
  Projects/Core/Sources/Repositories/UserRepository.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
Labels: ♻️ 리팩토링, ✨ 기능

#59 #29 / InformationView UI 구현
  Projects/Core/Sources/Common/Componets/DividerView.swift
  Projects/Core/Sources/Common/Componets/TasteScoreView.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Models/MakHoly/Award.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/Comment.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/LikeDetail.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/LikeState.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/MyComment.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/VisibleComment.swift
  Projects/Core/Sources/Models/User/User.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/DesignSystem/Sources/Colors/Color+.swift
  Projects/DesignSystem/Sources/Fonts/Font+.swift
  Projects/DesignSystem/Sources/Fonts/Font.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureHome/Scene/Characteristics/CharacteristicsView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemView.swift
  Projects/FeatureInformation/Scene/Components/InfoIngredientsView.swift
  Projects/FeatureInformation/Scene/Components/InfoLinkView.swift
  Projects/FeatureInformation/Scene/Components/LikeControllerView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoAwardsView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoImageView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoNameView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InformationCardView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoDescriptionView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoIngredientsView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikePercentageView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLinkView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InformationDetailView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureProfile/Scene/MyInformation/MyInformationView.swift
  Projects/FeatureProfile/Scene/SettingList/SettingListView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ✨ 기능, 💄 UI

#60 #58/Onboarding UI
  Projects/Core/Sources/Common/Componets/UnderlineView.swift
  Projects/Core/Sources/Common/Extensions/View+.swift
  Projects/Core/Sources/Models/User/SexType.swift
  Projects/Core/Sources/Network/Response/User/UserResponse.swift
  Projects/DesignSystem/Resources/Images.xcassets/Profile/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileAspartameFree.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileAspartameFree.imageset/profileAspartameFree.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileCarbonicAcid.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileCarbonicAcid.imageset/profileCarbonicAcid.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileHighlyHydrated.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileHighlyHydrated.imageset/profileHighlyHydrated.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSour.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSour.imageset/profileSour.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSweet.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSweet.imageset/profileSweet.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileThick.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileThick.imageset/profileThick.svg
  Projects/DesignSystem/Sources/Fonts/Font+.swift
  Projects/DesignSystem/Sources/Fonts/Font.swift
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureAuth/Scene/AuthView.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureOnboarding/Scene/OnboardingView.swift
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/Utils/Sources/KeyChain/KeyChainAccount.swift
  Projects/Utils/Sources/KeyChain/KeyChainManager.swift
  Projects/Utils/Sources/UserDefault/UserDefaultsSetting.swift
  Projects/Utils/Sources/UserDefault/UserDefaultsWrapper.swift
Labels: ✨ 기능, 💄 UI

#63 #61 / fetchDetail 구현
  Projects/App/Support/Info.plist
  Projects/Core/Sources/Common/Componets/TasteScoreView.swift
  Projects/Core/Sources/Common/Extensions/Double+.swift
  Projects/Core/Sources/Common/Extensions/Int+.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Models/MakHoly/BasicInfo.swift
  Projects/Core/Sources/Models/MakHoly/Brewery.swift
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/MyComment.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/MyReaction.swift
  Projects/Core/Sources/Models/MakHoly/Taste.swift
  Projects/Core/Sources/Network/MakgeolliAPI.swift
  Projects/Core/Sources/Network/Request/MakInfo/DetailRequest.swift
  Projects/Core/Sources/Network/Response/MakInfo/DetailResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InformationCardView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
Labels: ♻️ 리팩토링, ✨ 기능

#67 #64/전체 평가 및 댓글 API 연결
  Projects/Core/Sources/Models/MakHoly/Reaction/LikeDetail.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/VisibleComment.swift
  Projects/Core/Sources/Network/Response/MakInfo/MakLikesAndCommentsResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
Labels: ✨ 기능

#66 #36/Home UI 데이터 연결
  Projects/App/Sources/App.swift
  Projects/Core/Sources/Models/Characteristics/CharacteristicsType.swift
  Projects/Core/Sources/Network/MakgeolliAPI.swift
  Projects/Core/Sources/Network/Response/Home/NewMakListResponse.swift
  Projects/Core/Sources/Network/Response/Home/RecentCommentsResponse.swift
  Projects/Core/Sources/Network/Response/MakInfo/FindByFeaturesResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/DesignSystem/Resources/Images.xcassets/banner.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/banner.imageset/banner.png
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/FeatureAuth/Scene/AuthView.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/Hashtag/HashtagSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentSingleView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemView.swift
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/Utils/Sources/KeyChain/KeyChainManager.swift
Labels: ♻️ 리팩토링, ✨ 기능

#69 #65/막걸리 평가 API 구현
  Projects/Core/Sources/Network/Request/User/EvaluateMakRequest.swift
  Projects/Core/Sources/Network/Response/User/EvaluateMakResponse.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
Labels: ✨ 기능

#71 #40/Profile UI 데이터 연결
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/FeatureProfile/Scene/MyInformation/MyInformationView.swift
  Projects/FeatureProfile/Scene/ProfileView.swift
  Projects/Utils/Sources/UserDefault/UserDefaultsSetting.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#74 #73/MakHoly MyReaction 타입 분리
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/Core/Sources/Network/Response/MakInfo/DetailResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
Labels: ♻️ 리팩토링

#79 #75/찜하기 구현
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/bookMarked.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/bookMarked.imageset/bookMarked.svg
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/informtaionBackButton.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/informtaionBackButton.imageset/informtaionBackButton.svg
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/notBookMarked.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/notBookMarked.imageset/notBookMarked.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureInformation/Scene/ToolBarItem/InfoBackButton.swift
  Projects/FeatureInformation/Scene/ToolBarItem/InfoBookMarkButton.swift
Labels: ✨ 기능, 💄 UI

#78 #72/SearchView 데이터 연결
  Projects/Core/Sources/Network/Response/Search/SearchResponse.swift
  Projects/DesignSystem/Resources/Images.xcassets/character.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/character.imageset/character.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryControllerView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryListView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ♻️ 리팩토링, ✨ 기능

#80 #76/InfoLikeCommentDetailView 구현
  Projects/Core/Sources/Network/Response/MakInfo/MakLikesAndCommentsResponse.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentDetailView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
Labels: ✨ 기능, 💄 UI

#77 #70/내막걸리View API 데이터 적용
  Projects/Core/Sources/Network/Request/User/CommentRequest.swift
  Projects/Core/Sources/Network/Request/User/GetUserMakFolderRequest.swift
  Projects/Core/Sources/Network/Response/User/GetUserMakFolderResponse.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
  Projects/FeatureEncyclopedia/Scene/Tab/TabMenuView.swift
  Projects/FeatureEncyclopedia/Scene/Tab/TabNameView.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/Comment/CommentEditView.swift
  Projects/FeatureEncyclopedia/Scene/View/Comment/CustomActionSheet.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#86 #84/mock data set
  Projects/Core/Sources/Models/Characteristics/CharacteristicsType.swift
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
Labels: ♻️ 리팩토링, 💄 UI

#85 #68/코멘트로직구현
  Projects/Core/Sources/Common/Componets/CommentEditSheet.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/MyComment.swift
  Projects/Core/Sources/Network/Request/User/CommentRequest.swift
  Projects/Core/Sources/Network/Response/MakInfo/DetailResponse.swift
  Projects/Core/Sources/Network/Response/User/CommentResponse.swift
  Projects/Core/Sources/Repositories/UserRepository.swift
  Projects/DesignSystem/Resources/Images.xcassets/CommentEditSheet/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/CommentEditSheet/visibleFalse.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/CommentEditSheet/visibleFalse.imageset/visibleFalse.svg
  Projects/DesignSystem/Resources/Images.xcassets/CommentEditSheet/visibleTrue.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/CommentEditSheet/visibleTrue.imageset/visibleTrue.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/DesignSystem/Sources/View/View+.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryView.swift
Labels: ✨ 기능, 💄 UI

#90 #82/디자인 QA
  Projects/Core/Sources/Common/Componets/UnderlineView.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Models/Category/CategoryType.swift
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileAspartameFree.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileAspartameFree.imageset/profileAspartameFree.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileAspartameFree.imageset/profileAspartameFree.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileCarbonicAcid.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileCarbonicAcid.imageset/profileCarbonicAcid.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileCarbonicAcid.imageset/profileCarbonicAcid.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileHighlyHydrated.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileHighlyHydrated.imageset/profileHighlyHydrated.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileHighlyHydrated.imageset/profileHighlyHydrated.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSour.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSour.imageset/profileSour.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSour.imageset/profileSour.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSweet.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSweet.imageset/profileSweet.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileSweet.imageset/profileSweet.svg
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileThick.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileThick.imageset/profileThick.png
  Projects/DesignSystem/Resources/Images.xcassets/Profile/profileThick.imageset/profileThick.svg
  Projects/DesignSystem/Resources/Images.xcassets/Tab/home.imageset/home.svg
  Projects/DesignSystem/Resources/Images.xcassets/banner.imageset/banner.png
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/Hashtag/HashtagSingleView.swift
  Projects/FeatureCategory/Scene/Hashtag/HashtagView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentSingleView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentView.swift
  Projects/FeatureHome/Scene/Characteristics/CharacteristicsView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemView.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureOnboarding/Scene/OnboardingView.swift
  Projects/FeatureProfile/Scene/MyInformation/MyInformationView.swift
  Projects/FeatureProfile/Scene/SettingList/SettingListView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultSingleView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ♻️ 리팩토링, 💄 UI

#91 #88/InformationView 디자인 QA 수정
  Projects/Core/Sources/Common/Componets/CommentEditSheet.swift
  Projects/Core/Sources/Common/Componets/TasteScoreView.swift
  Projects/Core/Sources/Models/Image/ImageType.swift
  Projects/Core/Sources/Models/ViewType/CategoryType.swift
  Projects/Core/Sources/Models/ViewType/CommentEditState.swift
  Projects/DesignSystem/Sources/Colors/Color+.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoAwardsView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoImageView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoNameView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InformationCardView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentDetailView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLinkView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InformationDetailView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
Labels: ✨ 기능, 🐞 버그, 💄 UI

#92 디자인QA/#89
  Projects/Core/Sources/Network/Request/User/CommentRequest.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/Comment/CommentEditView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#96 #93/1차 마무리 작업
  Projects/Core/Sources/Common/Componets/MakHolyImageView.swift
  Projects/Core/Sources/Models/Image/ImageType.swift
  Projects/Core/Sources/Models/ViewType/CategoryType.swift
  Projects/Core/Sources/Network/Request/MakInfo/MakLikesAndCommentsRequest.swift
  Projects/Core/Sources/Network/Request/User/GetUserMakFolderRequest.swift
  Projects/Core/Sources/Network/Response/MakInfo/MakLikesAndCommentsResponse.swift
  Projects/Core/Sources/Repositories/MakgeolliRepository.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/Comment/CommentEditView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
  Projects/FeatureHome/Scene/Characteristics/CharacteristicsView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/FeatureProfile/Scene/MyInformation/MyInformationView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#95 #88/InformationView QA 수정
  Projects/Core/Sources/Common/Componets/CommentEditSheet.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Models/MakHoly/Reaction/LikeDetail.swift
  Projects/Core/Sources/Network/Request/User/GetUserMakFolderRequest.swift
  Projects/Core/Sources/Network/Response/Search/SearchResponse.swift
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/bookMarked.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/bookMarked.imageset/bookMarked.svg
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/informtaionBackButton.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/informtaionBackButton.imageset/informtaionBackButton.svg
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/notBookMarked.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/ToolBarItem/notBookMarked.imageset/notBookMarked.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoAwardsView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoDescriptionView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentDetailView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikePercentageView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLinkView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/ToolBarItem/InfoBackButton.swift
  Projects/FeatureInformation/Scene/ToolBarItem/InfoBookMarkButton.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
Labels: ✨ 기능, 🐞 버그, 💄 UI

#97 InformationView 연결하기
  Projects/Core/Sources/Common/Extensions/Int+.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoSingleView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemView.swift
Labels: ✨ 기능

#100 연결 찐막
  Projects/Core/Sources/Models/MakHoly/MakHoly.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryControllerView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ✨ 기능, 💄 UI

#103 #99/주룩 막걸리 이미지 그레이 스케일 적용
  Projects/Core/Sources/Common/Componets/MakHolyImageView.swift
Labels: ✨ 기능, 💄 UI

#106 🔨 [chore] 기존 수상작 배너 이미지 변경#105
  Projects/DesignSystem/Resources/Images.xcassets/banner.imageset/banner.png
Labels: 💄 UI

#104 #101/1차 마무리 QA
  Projects/Core/Sources/Models/MakHoly/MakHolyTestData.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentView.swift
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentView.swift
  Projects/FeatureOnboarding/Scene/OnboardingView.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#108 내막걸리View 2차 QA/#102
  Projects/FeatureEncyclopedia/Scene/EncyclopediaView.swift
  Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#109 QA 찐막
  Projects/Core/Sources/Models/MakHoly/Reaction/MyComment.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryListView.swift
Labels: ✨ 기능, 🐞 버그

#113 #110/MakHolyImageView개선
  Projects/App/Support/Info.plist
  Projects/Core/Sources/Common/Componets/MakHolyImageView.swift
  Projects/Core/Sources/Models/Image/ImageType.swift
  Projects/DesignSystem/Resources/Images.xcassets/errorImage.imageset/errorImage.png
  Projects/FeatureInformation/Scene/InformationView.swift
Labels: ✨ 기능

#119 #118/MakHolyImageView 개선
  Projects/Core/Sources/Common/Componets/MakHolyImageView.swift
Labels: 🐞 버그, 💄 UI

#123 #122/InformationView UI 개선
  Projects/Core/Sources/Models/MakHoly/Reaction/LikeDetail.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoIngredientsView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikePercentageView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
Labels: 💄 UI

#121 #114/라벨링 스캔
  Projects/App/Support/Info.plist
  Projects/Core/Sources/Models/Characteristics/CharacteristicsType.swift
  Projects/DesignSystem/Resources/Images.xcassets/Tab/camera.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Tab/camera.imageset/camera.svg
  Projects/DesignSystem/Resources/Images.xcassets/shutter.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/shutter.imageset/shutter.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/Feature/Project.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureCamera/Project.swift
  Projects/FeatureCamera/Scene/Camera.swift
  Projects/FeatureCamera/Scene/CameraView.swift
  Projects/FeatureCamera/Scene/CameraViewModel.swift
  Projects/Utils/Project.swift
  Projects/Utils/Sources/ImagePredictor/ImagePredictor.swift
  Projects/Utils/Sources/ImagePredictor/MakHolyLabelModel.mlmodel
  Tuist/ProjectDescriptionHelpers/Dependency+Project.swift
Labels: ✨ 기능, 💄 UI

#126 #125/버그 수정 및 ViewModel 수정
  Projects/Core/Sources/Common/Componets/TasteGraphView.swift
  Projects/Core/Sources/Network/Response/Home/NewMakListResponse.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ♻️ 리팩토링, 🐞 버그

#127 2차 업데이트/#117
  Projects/Core/Sources/Network/Response/Home/RecentCommentsResponse.swift
  Projects/Core/Sources/Network/Response/Search/SearchResponse.swift
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/circle.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/circle.imageset/circle.svg
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/numBox.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/numBox.imageset/numBox.svg
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/numBox_warmRed.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Tab2/numBox_warmRed.imageset/numBox_warmRed.svg
  Projects/DesignSystem/Sources/Images/Asset.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureOnboarding/Scene/BirthView.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureOnboarding/Scene/GenderView.swift
  Projects/FeatureOnboarding/Scene/NicknameView.swift
  Projects/FeatureOnboarding/Scene/PhoneNumberAuthView.swift
Labels: ✨ 기능, 💄 UI

#132 #129/온보딩 2차
  Projects/Core/Sources/Common/Componets/AlertItem.swift
  Projects/Core/Sources/Common/Componets/BackgroundModifier.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Feature/Project.swift
  Projects/FeatureAuth/Project.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureOnboarding/Scene/Auth/BirthView.swift
  Projects/FeatureOnboarding/Scene/Auth/GenderView.swift
  Projects/FeatureOnboarding/Scene/Auth/NicknameView.swift
  Projects/FeatureOnboarding/Scene/Auth/PhoneNumberAuthView.swift
  Projects/FeatureOnboarding/Scene/BirthView.swift
  Projects/FeatureOnboarding/Scene/CustomizationInfo/CustomizationInfoView.swift
  Projects/FeatureOnboarding/Scene/GenderView.swift
  Projects/FeatureOnboarding/Scene/NicknameView.swift
  Projects/FeatureOnboarding/Scene/OnboardingView.swift
  Projects/FeatureOnboarding/Scene/PhoneNumberAuthView.swift
  Projects/FeatureOnboarding/Scene/Skip/SkipGenderAndBirthView.swift
  Projects/FeatureOnboarding/Scene/Skip/SkipNicknameView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Project.swift
  Workspace.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#136 #124/홈 UI 변경사항 적용
  Projects/Core/Sources/Common/Componets/TasteGraphView.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/FeatureCategory/Scene/CategoryViewModel.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentSingleView.swift
  Projects/FeatureEncyclopedia/Scene/View/Comment/CommentContentsView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureHome/Scene/NewItem/NewItemSingleView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoMyCommentView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoCommentsListView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentDetailView.swift
Labels: ✨ 기능

#137 #120/믹스패널 ver1
  Projects/App/Sources/App.swift
  Projects/App/Support/Info.plist
  Projects/Core/Project.swift
  Projects/Core/Sources/Common/Extensions/String+.swift
  Projects/Core/Sources/Mixpanel/MixpanelManager.swift
  Projects/Core/Sources/Mixpanel/Modal/MPEvent.swift
  Projects/Core/Sources/Mixpanel/Modal/MPInfoActionCount.swift
  Projects/Core/Sources/Mixpanel/Modal/MPInfoClosedParameters.swift
  Projects/Core/Sources/Mixpanel/Modal/MPPreviousView.swift
  Projects/Core/Sources/Mixpanel/Modal/MPPropertiable.swift
  Projects/Core/Sources/Mixpanel/Modal/MPSearchMethod.swift
  Projects/Core/Sources/Mixpanel/Modal/MPSignUpMethod.swift
  Projects/Core/Sources/Mixpanel/Modal/MPUserCount.swift
  Projects/Feature/Scene/RootView.swift
  Projects/FeatureCategory/Scene/CategoryView.swift
  Projects/FeatureCategory/Scene/MakgeolliInformation/MakgeolliInfoView.swift
  Projects/FeatureCategory/Scene/NewComment/NewCommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/AllView.swift
  Projects/FeatureEncyclopedia/Scene/View/BookmarkView.swift
  Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
  Projects/FeatureEncyclopedia/Scene/View/DislikeView.swift
  Projects/FeatureEncyclopedia/Scene/View/LikeView.swift
  Projects/FeatureHome/Scene/HomeView.swift
  Projects/FeatureHome/Scene/HomeViewModel.swift
  Projects/FeatureHome/Scene/LatestComment/LatestCommentSingleView.swift
  Projects/FeatureInformation/Scene/InformationCardView/InfoLikeView.swift
  Projects/FeatureInformation/Scene/InformationDetailView/InfoLikeCommentView/InfoLikeCommentView.swift
  Projects/FeatureInformation/Scene/InformationView.swift
  Projects/FeatureInformation/Scene/InformationViewModel.swift
  Projects/FeatureInformation/Scene/ToolBarItem/InfoBackButton.swift
  Projects/FeatureOnboarding/Scene/Auth/LoadDataView.swift
  Projects/FeatureOnboarding/Scene/Auth/PhoneNumberAuthView.swift
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/FeatureOnboarding/Scene/SubRootView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
Labels: ⚙️ 설정, ✨ 기능

#139 #138/2차버전 찐막 QA
  Projects/App/Support/Info.plist
  Projects/FeatureOnboarding/Scene/Auth/NicknameView.swift
  Projects/FeatureOnboarding/Scene/OnboardingViewModel.swift
  Projects/FeatureOnboarding/Scene/Skip/SkipGenderAndBirthView.swift
  Projects/FeatureProfile/Scene/MyInformation/EditProfileView.swift
  Projects/FeatureProfile/Scene/ProfileViewModel.swift
  Projects/FeatureProfile/Scene/SettingList/SettingListView.swift
  Projects/FeatureSearch/Scene/SearchHistoryView/SearchHistoryControllerView.swift
  Projects/FeatureSearch/Scene/SearchResultView/SearchResultView.swift
  Projects/FeatureSearch/Scene/SearchView.swift
  Projects/FeatureSearch/Scene/SearchViewModel.swift
Labels: ✨ 기능, 🐞 버그
